import "dotenv/config";

const envConfig = {
  MONGODB_URL: process.env.MONGODB_URL || "",
  JWT_SECRET: process.env.JWT_SECRET || "",
  NEXTAUTH_URL: process.env.NEXTAUTH_URL || "",
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET || "",

  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY || "",
  STRIPE_PUBLIC_KEY: process.env.STRIPE_PUBLIC_KEY || "", 
  WEBHOOK_SECRET: process.env.WEBHOOK_SECRET || "",

  STRIPE_PRICE_MONTHLY_BASIC: process.env.NEXT_PUBLIC_STRIPE_PRICE_MONTHLY_BASIC || "",
  STRIPE_PRICE_MONTHLY_INTERMEDIATE: process.env.NEXT_PUBLIC_STRIPE_PRICE_MONTHLY_INTERMEDIATE || "",
  STRIPE_PRICE_MONTHLY_PRO: process.env.NEXT_PUBLIC_STRIPE_PRICE_MONTHLY_PRO || "",
  STRIPE_PRICE_YEARLY_BASIC: process.env.NEXT_PUBLIC_STRIPE_PRICE_YEARLY_BASIC || "",
  STRIPE_PRICE_YEARLY_INTERMEDIATE: process.env.NEXT_PUBLIC_STRIPE_PRICE_YEARLY_INTERMEDIATE || "",
  STRIPE_PRICE_YEARLY_PRO: process.env.NEXT_PUBLIC_STRIPE_PRICE_YEARLY_PRO || "",

  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL || "",
};

export default envConfig;
